![example](images/director_shot.jpeg)

# Project Title

**Authors:** Student 1, Student 2, Student 3
***

## Overview

A one-paragraph overview of the project, including the business problem, data, methods, results and recommendations.

## Business Problem

Summary of the business problem you are trying to solve, and the data questions that you plan to answer to solve them.

***
Questions to consider:
* What are the business's pain points related to this project?
* How did you pick the data analysis question(s) that you did?
* Why are these questions important from a business perspective?
***

## Data Understanding

Describe the data being used for this project.
***
Questions to consider:
* Where did the data come from, and how do they relate to the data analysis questions?
* What do the data represent? Who is in the sample and what variables are included?
* What is the target variable?
* What are the properties of the variables you intend to use?
***

In [1]:
# Import standard packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
# Here you run your code to explore the data

In [3]:
df = pd.read_csv('data/Pet_Supplies.csv')
df.head()

   0972585419  A13K4OZKAAHOXS  3.0  1190851200
0  0972585419  A1DWYEX4P7GB7Z  4.0  1188000000
1  0972585419  A3NVN97YJSKEPC  4.0  1171929600
2  0972585419  A1PDMES1LYA0DP  1.0  1483056000
3  0972585419   AT6BH0TQLZS5X  1.0  1482451200
4  0972585419  A2SQLP4B8T8V0V  4.0  1481587200

In [8]:
names = pd.read_json('data/Pet_Supplies_5.json.gz', lines=True)
names

,overall,vote,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,style,image
0,3,2,True,"12 2, 2016",A2KN4FJVI2TZSF,0972585419,M.G.,I purchased this cd for my Pocket Parrot. It h...,It's okay,1480636800,NaN,NaN
1,3,NaN,True,"10 17, 2016",A3RMA1DD66JDRV,0972585419,Susan P.,"Maybe it's just my Amazon parrot, but she's no...",It might work for a different bird,1476662400,NaN,NaN
2,5,2,True,"09 9, 2016",AAANYRIEOIT3R,0972585419,Luggie Lugnut,I bought this to help me teach my blue quaker ...,I bought this to help me teach my blue quaker ...,1473379200,NaN,NaN
3,3,NaN,True,"08 31, 2016",A3W44VX0LXAOHU,0972585419,Melissa Partin,Bird showed no interest in it....,Three Stars,1472601600,NaN,NaN
4,2,NaN,True,"08 18, 2016",A16ZDBZGKYDRSU,0972585419,Cheryle Bell,Didn't do a thing for my African Grey! He hate...,He hated it and it was very obnoxious,1471478400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2098320,4,NaN,True,"06 1, 2018",A2BWOAJ5KSAL4C,B01HIQ9NGU,TexasHonda,"It did no harm, but hard to see any improvemen...",Four Stars,1527811200,"{'Style:': ' 1 Box, 30 Packets'}",NaN
2098321,4,NaN,True,"11 26, 2017",A1X0IOOF3J0OXB,B01HIV7FC4,Pamela Mathers,These are not rounded. I bought them for my li...,Read description carefully.,1511654400,NaN,NaN
2098322,5,NaN,True,"09 21, 2017",A3UCIDW3BYEGB1,B01HIV7FC4,pterri,My destroyer French Bulldog was not able to de...,Sturdy Squeaker,1505952000,NaN,NaN
2098323,4,NaN,True,"06 16, 2017",A2JO0GAAKLQ0SH,B01HIV7FC4,Erik,"This is one of my dog's favorite toys, but all...","Dog loves it, but the squeakers don't last",1497571200,NaN,NaN
2098324,5,NaN,True,"05 4, 2017",A2UXNZY0ZUHYLF,B01HIV7FC4,PrimeAmazonLover,Best toy we've purchased for our new puppy. Ea...,Best toy we've purchased for our new puppy,1493856000,NaN,NaN

## Data Preparation

Describe and justify the process for preparing the data for analysis.

***
Questions to consider:
* Were there variables you dropped or created?
* How did you address missing values or outliers?
* Why are these choices appropriate given the data and the business problem?
***

In [6]:
# Here you run your code to clean the data

## Data Modeling
Describe and justify the process for analyzing or modeling the data.

***
Questions to consider:
* How did you analyze or model the data?
* How did you iterate on your initial approach to make it better?
* Why are these choices appropriate given the data and the business problem?
***

In [ ]:
# Here you run your code to model the data

## Evaluation
Evaluate how well your work solves the stated business problem.

***
Questions to consider:
* How do you interpret the results?
* How well does your model fit your data? How much better is this than your baseline model?
* How confident are you that your results would generalize beyond the data you have?
* How confident are you that this model would benefit the business if put into use?
***

## Conclusions
Provide your conclusions about the work you've done, including any limitations or next steps.

***
Questions to consider:
* What would you recommend the business do as a result of this work?
* What are some reasons why your analysis might not fully solve the business problem?
* What else could you do in the future to improve this project?
***